language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest -v --cov=fabular --cov-report=xml
  - pipenv run bandit fabular -r
