language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

before_script:
  - pipenv run pip install -e .

script:
  - pipenv run pytest -v --cov=fabular
  - pipenv run bandit src/ tests/ -r
